-- =========================================================
-- Category Embeddings Table — Day 6 DL Semantic Search
-- Stores a dense vector embedding (as JSON text) per category,
-- generated by scripts/build_embeddings.py using sentence-transformers.
-- =========================================================

DROP TABLE IF EXISTS category_embeddings;

CREATE TABLE category_embeddings (
    product_category_name VARCHAR(100) PRIMARY KEY,
    product_category_name_english VARCHAR(100),
    embedding_json LONGTEXT NOT NULL   -- JSON array of floats, e.g. "[0.012, -0.34, ...]"
);
